
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    lua_shared_dict item_cache 150m;  # 本地缓存，名称item_cache，大小150m
    include       mime.types;
    default_type  application/json;

    sendfile        on;
    
    keepalive_timeout  65;

     server {
        listen       80;
        server_name  localhost;
        # 指定前端项目所在的位置
        location / {
            root html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
    server {
        listen       18080;
        server_name  localhost;
        # 指定前端项目所在的位置
        location / {
            root html/hmall-portal;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        # 缓存单个商品详情
        location ~ ^/api/items/\d+$ {
            # 下面这行代码的意思是将请求转发给lua/item_detail.lua脚本处理
            content_by_lua_file lua/item_detail.lua;
        }

        # 缓存批量查询（可根据实际参数格式调整）
        location ~ ^/api/items(\?.*ids=.*)$ {
            # 下面这行代码的意思是将请求转发给lua/item_batch.lua脚本处理
            content_by_lua_file lua/item_batch.lua;
        }
        location /api {
            rewrite /api/(.*)  /$1 break;
            proxy_pass http://localhost:8080;
        }
    }
    server {
        listen       18081;
        server_name  localhost;
        # 指定前端项目所在的位置
        location / {
            root html/hmall-admin;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        location /api {
            rewrite /api/(.*)  /$1 break;
            proxy_pass http://localhost:8080;
        }
    }
    server {
        listen       18082;
        server_name  localhost;
        # 指定前端项目所在的位置
        location / {
            root html/hm-refresh-admin;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        location /api {
             proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Real-PORT $remote_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            rewrite /api/(.*)  /$1 break;
            proxy_pass http://localhost:8080;
        }
    }
    # upstream backend {
    #     server 127.0.0.1:8081 max_fails=5 fail_timeout=10s weight=1;
    #     server 127.0.0.1:8082 max_fails=5 fail_timeout=10s weight=1;
    # }  
}
